news:
  ligne1: "&a&l--------News--------"
  ligne2: "&l&fVoici les différentes News du serveur:"
  ligne3: " &l&f-Nouveau plugin de nightvision a partir du grade corrompu (&e/nightvision)"
  ligne4: " &l&f-Nouveau développeur: &cDarkYT_"
  ligne5: " &l&f-Nouveau développeur+: &4Shiick"
  ligne6: " &l&f-Un &e/helpme &fpour demander de l'aide"
  ligne7: " &l&f-Un panneau de repair pour les no-grades: coût &c1 coin &f(Mettre un panneau avec [REPAIR])"
  ligne8: "&a&l--------------------"