Liens:
  Boutique: "&6Boutique: &ehttp://boutique.com"
  Site: "&6Site: &ehttp://site.com"
  Chaine: "&cChaîne YouTube: &7http://youtube.com"
  Discord: "&9Discord: &7https://discord.gg/NEMQxyy"













































