Recycleur:
  Name: "&9Recycleur"
  Hopper: "&7Mettez votre item ci-dessous"
  Skull: "&9Explications"
  SkullLore1: "&7Mettez votre item"
  SkullLore2: "&7dans le recycleur"
  SkullLore3: "&7et recevez son"
  SkullLore4: "&7équivalent en matériaux."
  DiamondsItemsLore: "&6NonRecyclable"
  Confirm: "&a&lConfirmer le recyclage"
  Diamond: "&3Informations"
  DiamondLore1: "&7Les enchantements ne sont"
  DiamondLore2: "&7pas prit en compte."
  DiamondLore3: "&7Veillez à avoir de la place"
  DiamondLore4: "&7dans votre inventaire."
  Empty: "&3[&9Recycleur&3] &cIl n'y a pas d'objet dans le recycleur."
  Invalid: "&3[&9Recycleur&3] &cL'objet que vous avez mit dans le recycleur est invalide."
  NotRecyclable: "&3[&9Recycleur&3] &cL'objet que vous avez mit dans le recycleur est trop abimé pour être recyclé."
  Recycled: "&3[&9Recycleur&3] &aL'objet que vous avez mit dans le recycleur a bien été recyclé."
  NoAdminPerm: "&3[&9Recycleur&3] &cVous n'avez pas la permission de faire ceci."
  ConfigReload: "&3[&9Recycleur&3] &aConfig reload !"
  